# Generated by Django 4.0.1 on 2023-09-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_alter_entry_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='qr_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entry.qrcode'),
        ),
    ]
