# Generated by Django 4.0.1 on 2022-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_jobqualification_job_alter_apply_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
