# Generated by Django 4.0.1 on 2022-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_job_job_description_alter_job_qualifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-post_date',)},
        ),
        migrations.AddField(
            model_name='position',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
