# Generated by Django 4.0.1 on 2022-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_job_options_position_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='rank',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
