# Generated by Django 4.0.1 on 2022-05-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_position_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
