# Generated by Django 4.0.1 on 2022-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_has_children_application_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mother_name',
            field=models.CharField(max_length=150),
        ),
    ]
