# Generated by Django 4.0.1 on 2022-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_application_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='religion',
            field=models.CharField(choices=[('M', 'Muslim'), ('C', 'Christian'), ('O', 'Other')], max_length=1),
        ),
    ]
