# Generated by Django 4.0.1 on 2022-12-11 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0011_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_created=True)),
                ('application_status', models.CharField(choices=[('N', 'New'), ('O', 'On-Hold'), ('R', 'Rejected'), ('B', 'Black-List'), ('A', 'Accepted')], default='N', max_length=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('issued_by', models.ManyToManyField(related_name='issued_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
