# Generated by Django 4.0.1 on 2022-12-11 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0013_alter_applicationstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='issued_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
