# Generated by Django 4.0.1 on 2022-12-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_remove_applicationstatus_issued_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'ordering': ('-issue_date',), 'verbose_name_plural': 'Application Status'},
        ),
    ]
