# Generated by Django 4.0.1 on 2022-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_applicationstatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_skills', models.CharField(db_index=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Computer Skills',
            },
        ),
    ]
