# Generated by Django 4.0.1 on 2022-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_computerskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_skill', models.CharField(db_index=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Computer Skill',
            },
        ),
    ]
