# Generated by Django 4.0.1 on 2022-12-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_computerskill'),
        ('employee', '0009_alter_employeeskills_computer_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerSkills',
        ),
    ]
