# Generated by Django 4.0.1 on 2023-01-06 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationeducation',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
