# Generated by Django 4.0.1 on 2023-01-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_applicationeducation_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('position',)},
        ),
    ]
