# Generated by Django 4.0.1 on 2022-12-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_application',
        ),
    ]
